insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (1, 'Luohe', 1, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (2, 'El Zapotal del Norte', 5, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (3, 'Pedro Leopoldo', 3, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (4, 'Zhangxi', 2, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (5, 'Qingfeng', 1, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (6, 'Tertek', 10, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (7, 'Huanchillas', 8, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (8, 'Sidowayah Lor', 2, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (9, 'Zhanghekou', 5, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (10, 'Nanzhen', 7, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (11, 'Khosta', 10, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (12, 'Saint Paul', 9, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (13, 'Meipu', 10, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (14, 'Oslo', 5, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (15, 'Góis', 2, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (16, 'Schengen', 3, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (17, 'Virginia Beach', 8, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (18, 'Esil', 3, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (19, 'Matangshan', 7, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (20, 'Mabamba', 9, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (21, 'Bujanovac', 3, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (22, 'Novi Vinodolski', 2, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (23, 'Ushiku', 9, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (24, 'Piteå', 9, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (25, 'Sabugo', 9, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (26, 'Guanxi', 1, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (27, 'Talalayivka', 3, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (28, 'Suka Makmue', 5, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (29, 'Cancas', 5, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (30, 'Shiguai', 6, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (31, 'Forninho', 8, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (32, 'Tcholliré', 1, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (33, 'Dajasongai', 7, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (34, 'Veldhoven', 1, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (35, 'Shiyuetian', 1, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (36, 'Aleg', 1, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (37, 'Zhizhong', 6, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (38, 'Ural', 4, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (39, 'Netvořice', 3, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (40, 'Dongshe', 10, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (41, 'Thiès Nones', 8, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (42, 'Jipijapa', 2, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (43, 'Lishu', 2, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (44, 'Binitayan', 8, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (45, 'Gaofeng', 1, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (46, 'Unidad', 2, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (47, 'Mujur Satu', 1, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (48, 'Dolsk', 8, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (49, 'Grujugan', 2, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (50, 'Bartošovice', 9, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (51, 'Khonj', 6, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (52, 'Toulon', 9, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (53, 'Dasol', 5, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (54, 'Valença', 9, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (55, 'Tutong', 3, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (56, 'Mocímboa', 4, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (57, 'Sintung Timur', 2, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (58, 'Dampol', 10, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (59, 'Qaram Qōl', 9, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (60, 'Shihudang', 4, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (61, 'Wonosari', 2, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (62, 'Elaiochóri', 5, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (63, 'Malaga', 3, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (64, 'Tapacocha', 8, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (65, 'Kaliska', 5, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (66, 'Areia Branca', 10, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (67, 'Barra', 7, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (68, 'El Socorro', 2, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (69, 'Lubowidz', 6, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (70, 'Longcheng', 8, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (71, 'Dulce Nombre', 10, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (72, 'Tibati', 3, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (73, 'Shilovo', 1, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (74, 'Redinha', 7, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (75, 'Tokombere', 4, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (76, 'Trat', 5, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (77, 'Chongwen', 6, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (78, 'San Enrique', 1, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (79, 'Ventersdorp', 5, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (80, 'Kuantan', 8, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (81, 'Oygon', 5, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (82, 'Masons Bay', 5, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (83, 'Mokil', 10, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (84, 'Phoenix', 5, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (85, 'Ban Phue', 8, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (86, 'Santa Tecla', 9, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (87, 'Mirny', 10, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (88, 'Dobryatino', 1, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (89, 'Chuzhou', 10, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (90, 'Makale', 6, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (91, 'Keffi', 1, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (92, 'Skellefteå', 8, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (93, 'Jiaogong', 9, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (94, 'Prengtale', 8, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (95, 'Hufeng', 10, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (96, 'Fria', 7, 0);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (97, 'Belén Gualcho', 10, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (98, 'Maoyang', 9, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (99, 'Ngembel', 8, 1);
insert into preference (`id`, `preference_name`, `preference_score`, `preference_value`) values (100, 'Mlimba', 5, 0);
