insert into spot (`spot_id`, `spot_name`) values (1, 'Labuhankananga');
insert into spot (`spot_id`, `spot_name`) values (2, 'Solnechnogorsk');
insert into spot (`spot_id`, `spot_name`) values (3, 'Succha');
insert into spot (`spot_id`, `spot_name`) values (4, 'Oumiao');
insert into spot (`spot_id`, `spot_name`) values (5, 'La’ershan');
insert into spot (`spot_id`, `spot_name`) values (6, 'Lixi');
insert into spot (`spot_id`, `spot_name`) values (7, 'Bárrio');
insert into spot (`spot_id`, `spot_name`) values (8, 'Oneop');
insert into spot (`spot_id`, `spot_name`) values (9, 'Molave');
insert into spot (`spot_id`, `spot_name`) values (10, 'Barreiras');
insert into spot (`spot_id`, `spot_name`) values (11, 'Uga');
insert into spot (`spot_id`, `spot_name`) values (12, 'Melaka');
insert into spot (`spot_id`, `spot_name`) values (13, 'Choco');
insert into spot (`spot_id`, `spot_name`) values (14, 'Montelíbano');
insert into spot (`spot_id`, `spot_name`) values (15, 'Stockholm');
insert into spot (`spot_id`, `spot_name`) values (16, 'Danville');
insert into spot (`spot_id`, `spot_name`) values (17, 'Masaya');
insert into spot (`spot_id`, `spot_name`) values (18, 'Ar Rawḑah');
insert into spot (`spot_id`, `spot_name`) values (19, 'Dulovo');
insert into spot (`spot_id`, `spot_name`) values (20, 'Salto de Pirapora');
insert into spot (`spot_id`, `spot_name`) values (21, 'Kwakoa');
insert into spot (`spot_id`, `spot_name`) values (22, 'Klagen');
insert into spot (`spot_id`, `spot_name`) values (23, 'Zapod');
insert into spot (`spot_id`, `spot_name`) values (24, 'Star’');
insert into spot (`spot_id`, `spot_name`) values (25, 'Rawasan');
insert into spot (`spot_id`, `spot_name`) values (26, 'Tumba');
insert into spot (`spot_id`, `spot_name`) values (27, 'Kolodenka');
insert into spot (`spot_id`, `spot_name`) values (28, 'Radzanów');
insert into spot (`spot_id`, `spot_name`) values (29, 'Jianjiang');
insert into spot (`spot_id`, `spot_name`) values (30, 'Saint Petersburg');
insert into spot (`spot_id`, `spot_name`) values (31, 'Municipio de Copacabana');
insert into spot (`spot_id`, `spot_name`) values (32, 'Manjakandriana');
insert into spot (`spot_id`, `spot_name`) values (33, 'Ithari');
insert into spot (`spot_id`, `spot_name`) values (34, 'Manzanares');
insert into spot (`spot_id`, `spot_name`) values (35, 'Wetzlar');
insert into spot (`spot_id`, `spot_name`) values (36, 'Kostrovo');
insert into spot (`spot_id`, `spot_name`) values (37, 'Brudzeń Duży');
insert into spot (`spot_id`, `spot_name`) values (38, 'Orsha');
insert into spot (`spot_id`, `spot_name`) values (39, 'Tanjung Raja');
insert into spot (`spot_id`, `spot_name`) values (40, 'Sukamahi Satu');
insert into spot (`spot_id`, `spot_name`) values (41, 'Shuishiying');
insert into spot (`spot_id`, `spot_name`) values (42, 'Mukacheve');
insert into spot (`spot_id`, `spot_name`) values (43, 'Nowosielce-Gniewosz');
insert into spot (`spot_id`, `spot_name`) values (44, 'Nova Cruz');
insert into spot (`spot_id`, `spot_name`) values (45, 'Kralice na Hané');
insert into spot (`spot_id`, `spot_name`) values (46, 'Malikisi');
insert into spot (`spot_id`, `spot_name`) values (47, 'Jenamas');
insert into spot (`spot_id`, `spot_name`) values (48, 'Lujing Zhen');
insert into spot (`spot_id`, `spot_name`) values (49, 'Samuhú');
insert into spot (`spot_id`, `spot_name`) values (50, 'Haduohe');
insert into spot (`spot_id`, `spot_name`) values (51, 'San Francisco');
insert into spot (`spot_id`, `spot_name`) values (52, 'Żarki');
insert into spot (`spot_id`, `spot_name`) values (53, 'Tbilisskaya');
insert into spot (`spot_id`, `spot_name`) values (54, 'Lo Prado');
insert into spot (`spot_id`, `spot_name`) values (55, 'Kesabpur');
insert into spot (`spot_id`, `spot_name`) values (56, 'Point Hill');
insert into spot (`spot_id`, `spot_name`) values (57, 'Conceição da Feira');
insert into spot (`spot_id`, `spot_name`) values (58, 'Chişinău');
insert into spot (`spot_id`, `spot_name`) values (59, 'Samadua');
insert into spot (`spot_id`, `spot_name`) values (60, 'Karibib');
insert into spot (`spot_id`, `spot_name`) values (61, 'Malaba');
insert into spot (`spot_id`, `spot_name`) values (62, 'Pridonskoy');
insert into spot (`spot_id`, `spot_name`) values (63, '‘Ubāl');
insert into spot (`spot_id`, `spot_name`) values (64, 'Morropón');
insert into spot (`spot_id`, `spot_name`) values (65, 'Esquipulas');
insert into spot (`spot_id`, `spot_name`) values (66, 'Huiwen');
insert into spot (`spot_id`, `spot_name`) values (67, 'Zhujiang');
insert into spot (`spot_id`, `spot_name`) values (68, 'San Martín de los Andes');
insert into spot (`spot_id`, `spot_name`) values (69, 'Orlová');
insert into spot (`spot_id`, `spot_name`) values (70, 'Sapeken');
insert into spot (`spot_id`, `spot_name`) values (71, 'Penggakrajeng');
insert into spot (`spot_id`, `spot_name`) values (72, 'Sundsvall');
insert into spot (`spot_id`, `spot_name`) values (73, 'Bīleh Savār');
insert into spot (`spot_id`, `spot_name`) values (74, 'Zhongfeng');
insert into spot (`spot_id`, `spot_name`) values (75, 'Laiponda');
insert into spot (`spot_id`, `spot_name`) values (76, 'Nowa Dęba');
insert into spot (`spot_id`, `spot_name`) values (77, 'Umi');
insert into spot (`spot_id`, `spot_name`) values (78, 'Isoka');
insert into spot (`spot_id`, `spot_name`) values (79, 'Góra');
insert into spot (`spot_id`, `spot_name`) values (80, 'Zachepylivka');
insert into spot (`spot_id`, `spot_name`) values (81, 'Wichit');
insert into spot (`spot_id`, `spot_name`) values (82, 'Khamyāb');
insert into spot (`spot_id`, `spot_name`) values (83, 'Boucinhas');
insert into spot (`spot_id`, `spot_name`) values (84, 'Velingrad');
insert into spot (`spot_id`, `spot_name`) values (85, 'Shebekino');
insert into spot (`spot_id`, `spot_name`) values (86, 'Vanadjou');
insert into spot (`spot_id`, `spot_name`) values (87, 'Liyang');
insert into spot (`spot_id`, `spot_name`) values (88, 'Kool Tengah');
insert into spot (`spot_id`, `spot_name`) values (89, 'Hechuan');
insert into spot (`spot_id`, `spot_name`) values (90, 'Polonnaruwa');
insert into spot (`spot_id`, `spot_name`) values (91, 'Huajie');
insert into spot (`spot_id`, `spot_name`) values (92, 'Tubel');
insert into spot (`spot_id`, `spot_name`) values (93, 'Chantilly');
insert into spot (`spot_id`, `spot_name`) values (94, 'Norsborg');
insert into spot (`spot_id`, `spot_name`) values (95, 'Bình Thủy');
insert into spot (`spot_id`, `spot_name`) values (96, 'Newark');
insert into spot (`spot_id`, `spot_name`) values (97, 'Jardinópolis');
insert into spot (`spot_id`, `spot_name`) values (98, 'Imrīsh');
insert into spot (`spot_id`, `spot_name`) values (99, 'Portarlington');
insert into spot (`spot_id`, `spot_name`) values (100, 'Muslyumovo');
